config/routes.rb
FunProj::Application.routes.draw do
  resources :sys_cleans

  resources :sys_checks

  resources :sys_ops

  resources :cals

  root :to => 'cals#index'

end

app/models/cal.rb
class Cal < ActiveRecord::Base
  # attr_accessible :title, :body
  has_calendar

end

app/models/sys_check.rb
class SysCheck < ActiveRecord::Base
  attr_accessible :hd_usage, :mem_usage, :sys_op_id, :time_running

  belongs_to :sys_op, :autosave => :true

  after_create :collect_data #tells method collect_data to run after creation of the report

  def collect_data
    #Put code to collect data here
  end
  handle_asynchronously :collect_data #This statement gives the method to our dj worker to complete the task

end

app/models/sys_clean.rb
class SysClean < ActiveRecord::Base
  attr_accessible :new_packages, :sys_op_id, :trash_bin_contents

  belongs_to :sys_op, :autosave => :true

  after_create :collect_data #tells method collect_data to run after creation of the report

  def collect_data
    #Put code to collect data here
  end
  handle_asynchronously :collect_data #This statement gives the method to our dj worker to complete the task

end

app/models/sys_op.rb
class SysOp < ActiveRecord::Base
  attr_accessible :start_time_column, :title

  has_one :sys_clean, :dependent => :destroy
  has_one :sys_check,	:dependent => :destroy

  validates_presence_of :title

  after_create :init_report

  def init_report
    if title == "Clean System Operation"
      self.create_sys_clean
    else
      self.create_sys_check
    end

    self.update_attributes(start_time_column: Time.now)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cals_controller.rb
class CalsController < ApplicationController
  # GET /cals
  # GET /cals.json
  def index
    @events = SysOp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cals }
    end
  end

end

app/controllers/sys_checks_controller.rb
class SysChecksController < ApplicationController
  # GET /sys_checks
  # GET /sys_checks.json
  def index
    @sys_checks = SysCheck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sys_checks }
    end
  end

  # GET /sys_checks/1
  # GET /sys_checks/1.json
  def show
    @sys_check = SysCheck.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sys_check }
    end
  end

  # GET /sys_checks/new
  # GET /sys_checks/new.json
  def new
    @sys_check = SysCheck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sys_check }
    end
  end

  # GET /sys_checks/1/edit
  def edit
    @sys_check = SysCheck.find(params[:id])
  end

  # POST /sys_checks
  # POST /sys_checks.json
  def create
    @sys_check = SysCheck.new(params[:sys_check])

    respond_to do |format|
      if @sys_check.save
        format.html { redirect_to @sys_check, notice: 'Sys check was successfully created.' }
        format.json { render json: @sys_check, status: :created, location: @sys_check }
      else
        format.html { render action: "new" }
        format.json { render json: @sys_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sys_checks/1
  # PUT /sys_checks/1.json
  def update
    @sys_check = SysCheck.find(params[:id])

    respond_to do |format|
      if @sys_check.update_attributes(params[:sys_check])
        format.html { redirect_to @sys_check, notice: 'Sys check was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sys_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sys_checks/1
  # DELETE /sys_checks/1.json
  def destroy
    @sys_check = SysCheck.find(params[:id])
    @sys_check.destroy

    respond_to do |format|
      format.html { redirect_to sys_checks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sys_cleans_controller.rb
class SysCleansController < ApplicationController
  # GET /sys_cleans
  # GET /sys_cleans.json
  def index
    @sys_cleans = SysClean.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sys_cleans }
    end
  end

  # GET /sys_cleans/1
  # GET /sys_cleans/1.json
  def show
    @sys_clean = SysClean.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sys_clean }
    end
  end

  # GET /sys_cleans/new
  # GET /sys_cleans/new.json
  def new
    @sys_clean = SysClean.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sys_clean }
    end
  end

  # GET /sys_cleans/1/edit
  def edit
    @sys_clean = SysClean.find(params[:id])
  end

  # POST /sys_cleans
  # POST /sys_cleans.json
  def create
    @sys_clean = SysClean.new(params[:sys_clean])

    respond_to do |format|
      if @sys_clean.save
        format.html { redirect_to @sys_clean, notice: 'Sys clean was successfully created.' }
        format.json { render json: @sys_clean, status: :created, location: @sys_clean }
      else
        format.html { render action: "new" }
        format.json { render json: @sys_clean.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sys_cleans/1
  # PUT /sys_cleans/1.json
  def update
    @sys_clean = SysClean.find(params[:id])

    respond_to do |format|
      if @sys_clean.update_attributes(params[:sys_clean])
        format.html { redirect_to @sys_clean, notice: 'Sys clean was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sys_clean.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sys_cleans/1
  # DELETE /sys_cleans/1.json
  def destroy
    @sys_clean = SysClean.find(params[:id])
    @sys_clean.destroy

    respond_to do |format|
      format.html { redirect_to sys_cleans_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sys_ops_controller.rb
class SysOpsController < ApplicationController

  # GET /sys_ops/1
  # GET /sys_ops/1.json
  def show
    @sys_op = SysOp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sys_op }
    end
  end

  # GET /sys_ops/new
  # GET /sys_ops/new.json
  def new
    @time = Time.now
    @sys_op = SysOp.new(:start_time_column => :@time)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sys_op }
    end
  end

  # GET /sys_ops/1/edit
  def edit
    @sys_op = SysOp.find(params[:id])
  end

  # POST /sys_ops
  # POST /sys_ops.json
  def create
    @sys_op = SysOp.new(params[:sys_op])

    respond_to do |format|
      if @sys_op.save
        format.html { redirect_to @sys_op, notice: 'Sys op was successfully created.' }
        format.json { render json: @sys_op, status: :created, location: @sys_op }
      else
        format.html { render action: "new" }
        format.json { render json: @sys_op.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sys_ops/1
  # PUT /sys_ops/1.json
  def update
    @sys_op = SysOp.find(params[:id])

    respond_to do |format|
      if @sys_op.update_attributes(params[:sys_op])
        format.html { redirect_to @sys_op, notice: 'Sys op was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sys_op.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sys_ops/1
  # DELETE /sys_ops/1.json
  def destroy
    @sys_op = SysOp.find(params[:id])
    @sys_op.destroy

    respond_to do |format|
      format.html { redirect_to sys_ops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cals_helper.rb
module CalsHelper
end

app/helpers/sys_checks_helper.rb
module SysChecksHelper
end

app/helpers/sys_cleans_helper.rb
module SysCleansHelper
end

app/helpers/sys_ops_helper.rb
module SysOpsHelper
end

app/views/cals/index.html.erb
<h1>System Events</h1>

<%= calendar @events do |event| %>
    <div><%= link_to event.title, (event.title == "Clean System Operation") ? sys_clean_path(event.sys_clean) : sys_check_path(event.sys_check) %></div>
<% end %>

<%= link_to 'New System Operation', new_sys_op_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunProj</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sys_checks/_form.html.erb
<%= form_for(@sys_check) do |f| %>
  <% if @sys_check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sys_check.errors.count, "error") %> prohibited this sys_check from being saved:</h2>

      <ul>
      <% @sys_check.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hd_usage %><br />
    <%= f.text_field :hd_usage %>
  </div>
  <div class="field">
    <%= f.label :mem_usage %><br />
    <%= f.text_field :mem_usage %>
  </div>
  <div class="field">
    <%= f.label :time_running %><br />
    <%= f.text_field :time_running %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sys_checks/edit.html.erb
<h1>Editing sys_check</h1>

<%= render 'form' %>

<%= link_to 'Show', @sys_check %> |
<%= link_to 'Back to calendar', cals_path %>

app/views/sys_checks/index.html.erb
<h1>Listing sys_checks</h1>

<table>
  <tr>
    <th>Hd usage</th>
    <th>Mem usage</th>
    <th>Time running</th>
    <th>Sys op</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sys_checks.each do |sys_check| %>
  <tr>
    <td><%= sys_check.hd_usage %></td>
    <td><%= sys_check.mem_usage %></td>
    <td><%= sys_check.time_running %></td>
    <td><%= sys_check.sys_op_id %></td>
    <td><%= link_to 'Show', sys_check %></td>
    <td><%= link_to 'Edit', edit_sys_check_path(sys_check) %></td>
    <td><%= link_to 'Destroy', sys_check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sys check', new_sys_check_path %>

app/views/sys_checks/new.html.erb
<h1>New sys_check</h1>

<%= render 'form' %>

<%= link_to 'Back', sys_checks_path %>

app/views/sys_checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hd usage:</b>
  <%= @sys_check.hd_usage %>
</p>

<p>
  <b>Mem usage:</b>
  <%= @sys_check.mem_usage %>
</p>

<p>
  <b>Time running:</b>
  <%= @sys_check.time_running %>
</p>

<p>
  <b>Sys op:</b>
  <%= @sys_check.sys_op_id %>
</p>


<%= link_to 'Edit', edit_sys_check_path(@sys_check) %> |
<%= link_to 'Back to calendar', cals_path %>

app/views/sys_cleans/_form.html.erb
<%= form_for(@sys_clean) do |f| %>
  <% if @sys_clean.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sys_clean.errors.count, "error") %> prohibited this sys_clean from being saved:</h2>

      <ul>
      <% @sys_clean.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trash_bin_contents %><br />
    <%= f.text_area :trash_bin_contents %>
  </div>
  <div class="field">
    <%= f.label :new_packages %><br />
    <%= f.text_area :new_packages %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sys_cleans/edit.html.erb
<h1>Editing sys_clean</h1>

<%= render 'form' %>

<%= link_to 'Show', @sys_clean %> |
<%= link_to 'Back to calendar', cals_path %>

app/views/sys_cleans/index.html.erb
<h1>Listing sys_cleans</h1>

<table>
  <tr>
    <th>Trash bin contents</th>
    <th>New packages</th>
    <th>Sys op</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sys_cleans.each do |sys_clean| %>
  <tr>
    <td><%= sys_clean.trash_bin_contents %></td>
    <td><%= sys_clean.new_packages %></td>
    <td><%= link_to 'Show', sys_clean %></td>
    <td><%= link_to 'Edit', edit_sys_clean_path(sys_clean) %></td>
    <td><%= link_to 'Destroy', sys_clean, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sys clean', new_sys_clean_path %>

app/views/sys_cleans/new.html.erb
<h1>New sys_clean</h1>

<%= render 'form' %>

<%= link_to 'Back', sys_cleans_path %>

app/views/sys_cleans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Trash bin contents:</b>
  <%= @sys_clean.trash_bin_contents %>
</p>

<p>
  <b>New packages:</b>
  <%= @sys_clean.new_packages %>
</p>

<p>
  <b>Sys op:</b>
  <%= @sys_clean.sys_op_id %>
</p>


<%= link_to 'Edit', edit_sys_clean_path(@sys_clean) %> |
<%= link_to 'Back to calendar', cals_path %>

app/views/sys_ops/_form.html.erb
<%= form_for(@sys_op) do |f| %>
  <% if @sys_op.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sys_op.errors.count, "error") %> prohibited this sys_op from being saved:</h2>

      <ul>
      <% @sys_op.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.select :title, ["Clean System Operation", "System Status Operation"] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sys_ops/edit.html.erb
<h1>Editing sys_op</h1>

<%= render 'form' %>

<%= link_to 'Show', @sys_op %> |
<%= link_to 'Back', sys_ops_path %>

app/views/sys_ops/new.html.erb
<h1>New sys_op</h1>

<%= render 'form' %>

<%= link_to 'Back', sys_ops_path %>

app/views/sys_ops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start time column:</b>
  <%= @sys_op.start_time_column %>
</p>

<p>
  <b>Title:</b>
  <%= @sys_op.title %>
</p>


<%= link_to 'Edit', edit_sys_op_path(@sys_op) %> |
<%= link_to 'Back', sys_ops_path %>